---
- name: Install Java 17 and Jenkins on Jenkins Master
  hosts: jenkins-master
  become: yes

  tasks:
    - name: Update apt package cache
      apt:
        update_cache: yes
      when: ansible_os_family == 'Debian'

    - name: Install OpenJDK 17
      apt:
        name: openjdk-17-jdk
        state: present
      when: ansible_os_family == 'Debian'

    - name: Add Jenkins repository key
      apt_key:
        url: https://pkg.jenkins.io/debian/jenkins.io-2023.key
      when: ansible_os_family == 'Debian'

    - name: Add Jenkins repository
      apt_repository:
        repo: 'deb http://pkg.jenkins.io/debian-stable binary/'
        state: present
      when: ansible_os_family == 'Debian'

    - name: Install Jenkins
      apt:
        name: jenkins
        state: present
      when: ansible_os_family == 'Debian'

    - name: Start Jenkins service
      systemd:
        name: jenkins
        state: started
        enabled: yes

