---
- name: Install Maven on remote server
  hosts: jenkins-slave  # Replace with the actual hostname or IP address of your slave server
  become: true  # Run tasks with sudo

  tasks:
    - name: Update package cache
      apt:
        update_cache: yes
      when: ansible_os_family == 'Debian'  # For Debian-based systems like Ubuntu

    - name: Install OpenJDK 17
      apt:
        name: openjdk-17-jdk
        state: present
      when: ansible_os_family == 'Debian'

    - name: Download Maven
      get_url:
        url: "https://dlcdn.apache.org/maven/maven-3/3.9.6/binaries/apache-maven-3.9.6-bin.tar.gz"
        dest: "/tmp/apache-maven-3.9.6-bin.tar.gz"

    - name: Extract Maven archive
      ansible.builtin.unarchive:
        src: "/tmp/apache-maven-3.9.6-bin.tar.gz"
        dest: "/opt/"
        remote_src: yes
        creates: "/opt/apache-maven-3.9.6"

    - name: Create symbolic link
      ansible.builtin.file:
        src: "/opt/apache-maven-3.9.6"
        dest: "/opt/maven"
        state: link

    - name: Set Maven environment variables
      ansible.builtin.lineinfile:
        path: "/etc/profile.d/maven.sh"
        line: 'export PATH=$PATH:/opt/maven/bin'
        create: yes

    - name: Reload shell environment
      ansible.builtin.shell:
        cmd: ". /etc/profile.d/maven.sh"

    - name: install docker 
      apt: 
        name: docker.io 
        state: present

    - name: start docker services 
      service: 
         name: docker 
         state: started 
  
    - name: give 777 permissions on /var/run/docker.sock
      file: 
        path: /var/run/docker.sock
        state: file 
        mode: 0777
        group: docker
          
    - name: start docker on boot time 
      service: 
        name: docker 
        enabled: yes

